# Generated by Django 5.0.6 on 2026-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_patrimonio', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('arma', 'Armamento'), ('expediente', 'Material de Expediente')], default='arma', max_length=20)),
                ('status', models.CharField(choices=[('operante', 'Operante'), ('defeito', 'Com Defeito'), ('manutencao', 'Em Manutenção')], default='operante', max_length=20)),
                ('motivo_defeito', models.TextField(blank=True, null=True)),
                ('localizacao_atual', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
