# Generated by Django 5.0.6 on 2026-06-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('arma', 'Armamento'), ('municao', 'Munição'), ('colete', 'Colete Balístico / EPI'), ('celular', 'Celular Institucional'), ('algemas', 'Algemas'), ('expediente', 'Material de Expediente'), ('outros', 'Outros (Cones, Extintores, etc)')], default='arma', max_length=20),
        ),
    ]
