# Generated by Django 5.0.6 on 2026-07-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_equipamento_observacoes_alter_equipamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='numero_patrimonio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='tipo',
            field=models.CharField(choices=[('arma', 'Armamento'), ('municao', 'Munição'), ('celular', 'SADE Celular inst.'), ('impressora', 'Impressora'), ('etilometro', 'Etilometro'), ('maleta', 'Maleta'), ('outros', 'Outros')], default='arma', max_length=20),
        ),
    ]
