# Generated by Django 5.0.6 on 2026-06-19 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroQuilometragem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_inicial', models.IntegerField()),
                ('km_final', models.IntegerField(blank=True, null=True)),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixo', models.CharField(max_length=50, unique=True)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('operante', 'Operante'), ('baixada_rodando', 'Baixada Rodando'), ('baixada', 'Baixada')], default='operante', max_length=20)),
                ('km_atual', models.IntegerField(default=0)),
                ('limite_troca_oleo', models.IntegerField(default=10000, help_text='KM limite para a próxima troca de óleo')),
                ('km_ultima_troca_oleo', models.IntegerField(default=0)),
                ('motivo_baixa', models.TextField(blank=True, null=True)),
                ('localizacao_atual', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
