# Generated by Django 5.0.6 on 2026-06-19 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo', models.TextField()),
                ('local', models.CharField(max_length=200)),
                ('data_retorno', models.DateTimeField(blank=True, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('viatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='frota.viatura')),
            ],
        ),
    ]
