# Generated by Django 5.0.6 on 2026-06-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0003_historicomanutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatura',
            name='marca',
            field=models.CharField(default='Não Informada', max_length=50),
        ),
        migrations.AddField(
            model_name='viatura',
            name='tipo',
            field=models.CharField(choices=[('carro', 'Carro'), ('moto', 'Moto'), ('furgao', 'Furgão'), ('outros', 'Outros')], default='carro', max_length=20),
        ),
    ]
