# Generated by Django 5.0.6 on 2026-07-01 11:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0005_aberturaturnoviatura'),
        ('ocorrencias', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='aberturaturnoviatura',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aberturaturnoviatura',
            name='data_abertura',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='aberturaturnoviatura',
            name='data_encerramento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aberturaturnoviatura',
            name='relatorio_turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abertura_turno', to='ocorrencias.relatorioturno'),
        ),
    ]
