# Generated by Django 5.0.6 on 2026-07-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frota', '0007_motorista_aberturaturnoviatura_motorista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatura',
            name='status',
            field=models.CharField(choices=[('operando', 'Operando(300)'), ('vai_baixar', 'Vai Baixar'), ('baixada_batalhao', 'Baixada(Batalhão)'), ('baixada_oficina', 'Baixada(Oficina)')], default='operando', max_length=20),
        ),
    ]
