# Generated by Django 5.0.6 on 2026-07-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha_provisoria',
            field=models.BooleanField(default=False),
        ),
    ]
