# Generated by Django 5.0.6 on 2026-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApreensaoDroga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medida', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('und', 'und'), ('ml', 'ml'), ('L', 'L')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artigo', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(choices=[('padrao', 'Padrão'), ('bloqueio', 'Bloqueio')], default='padrao', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetoApreendido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaAbordada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('condutor', 'Condutor'), ('passageiro', 'Passageiro'), ('transeunte', 'Transeunte')], max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PrisaoApreensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=15)),
                ('idade', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroBOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_numero', models.CharField(max_length=20)),
                ('natureza', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RelatorioTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('comandante', models.CharField(max_length=150)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('dinheiro_apreendido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TesteEtilometrico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizados', models.PositiveIntegerField(default=0)),
                ('recusas', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoAbordado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VeiculoRecolhido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('destino', models.CharField(choices=[('patio', 'Pátio da Cia PM'), ('delegacia', 'Delegacia'), ('recuperado_patio', 'Recuperado - Pátio'), ('recuperado_delegacia', 'Recuperado - Delegacia'), ('recuperado_outros', 'Recuperado - Outros')], max_length=30)),
            ],
        ),
    ]
