# Generated by Django 5.0.6 on 2026-06-19 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frota', '0002_initial'),
        ('ocorrencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorioturno',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relatorioturno',
            name='viatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='frota.viatura'),
        ),
        migrations.AddField(
            model_name='registrobou',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_bou', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='prisaoapreensao',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prisoes_apreensoes', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='pessoaabordada',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoas_abordadas', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='objetoapreendido',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos_apreendidos', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='notificacao',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='apreensaodroga',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drogas_apreendidas', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='testeetilometrico',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teste_etilometrico', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='veiculoabordado',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_abordados', to='ocorrencias.relatorioturno'),
        ),
        migrations.AddField(
            model_name='veiculorecolhido',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos_recolhidos', to='ocorrencias.relatorioturno'),
        ),
    ]
